// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"github.com/google/wire"
	"github.com/phuslu/log"
	"github.com/rabbitmq/amqp091-go"
	"github.com/redis/go-redis/v9"
	"gorm.io/gorm"

	"github.com/bagasunix/gosnix/internal/infrastructure/http/handlers"
	"github.com/bagasunix/gosnix/internal/infrastructure/repositories"
)

// Injectors from wire.go:

func InitializeHealthHandler(db *gorm.DB, redisClient *redis.Client, rabbitConn *amqp091.Connection, logger *log.Logger) *handlers.HealthHandler {
	repository := repositories.NewHealthRepo(logger, db, redisClient, rabbitConn)
	service := NewHealthService(repository)
	healthHandler := handlers.NewHealthHandler(service)
	return healthHandler
}

// wire.go:

var HealthSets = wire.NewSet(repositories.NewHealthRepo, NewHealthService, handlers.NewHealthHandler)
