basePath: /api
host: localhost:8080
info:
  contact:
    email: support@gosnix.local
    name: Developer Support
  description: API untuk sistem Gosnix
  termsOfService: http://swagger.io/terms/
  title: Gosnix API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
